# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    container_name: data-api
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=mongodb://data-api-mongodb:27017
    depends_on:
      - db
  db:
    image: mongo
    container_name: data-api-mongodb
    ports:
      - 27017:27017
    restart: unless-stopped